name: My Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build app
        run: |
          # Build your app here
          echo "SC_KEY" : ${{ vars.SC_KEY }}"
          echo "window.mySecret = '${{ secrets.MY_SECRET_NAME }}';" > secret.js
          # This generates a JavaScript file with the secret as a global variable
          
      - name: Deploy
        uses: some/deploy-action@v1

        
        
#           MY_SECRET_NAME: ${{ secrets.MY_SECRET_NAME }}
#         run: node secrets.js
